# Generated by Django 3.0.3 on 2021-06-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0002_auto_20210605_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(upload_to='styles/images'),
        ),
    ]
