# Generated by Django 3.0.3 on 2021-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0003_auto_20210605_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
