# Generated by Django 3.0.3 on 2021-06-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0004_auto_20210607_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='style',
            name='model',
            field=models.FileField(upload_to='model'),
        ),
    ]
