# Generated by Django 3.0.3 on 2021-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0005_auto_20210608_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.ImageField(upload_to='styles/images'),
        ),
        migrations.AlterField(
            model_name='style',
            name='model',
            field=models.FileField(upload_to='styles/models'),
        ),
    ]
